# Generated by Django 5.2.5 on 2025-08-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_order_full_name_remove_order_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default='no message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
