# Generated by Django 5.2.5 on 2025-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default='default title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
